seed: 1
dataset:
  name: "delay"
  epoch_size: 8192
  lag: 64
  n_categories: 16
  extra: 64
  auto_regressive: false
  copy_token: false
train:
  num_epochs: 1000
  batch_size: 8
  lr: 0.001
  stop_on_loss: 0.01
model:
  n_layers: 2
  d_model: 64
  d_state: 16
  ssm_type: "S4D-Real"
  vocab_size: 16
  pad_vocab_size_multiple: 16
  bidirectional: false
  use_cuda: true