seed: 1
wandb:
   entity: "complex-team"
   project: "InductionHead_break_S4"
dataset:
  name: "induction_head"
  epoch_size: 8192
  seq_len: 128
  n_categories: 16
  num_triggers: 1
  induction_len: 64
  auto_regressive: true
train:
  num_epochs: 1000
  batch_size: 8
  lr: 0.001
  stop_on_loss: 0.001
model:
  n_layers: 2
  d_model: 64
  d_state: 16
  ssm_type: "NoT_RELEVANT"
  vocab_size: 16
  pad_vocab_size_multiple: 16
  bidirectional: false
  BC_is_selective: false
  dt_is_selective: false
  bias: true
  channel_sharing: false
  use_cuda: false