seed: 1
N: 1024
complex_option: false
L: 32 # if None then L=N
task_name: "random"
opt: "adam"
num_epochs: 500000
use_wandb: true
lr: 0.00001
r_min: 0.99
BC_std: 0.001
wandb_project_name: "theory_real"